### ISSUE TITLE
About input 32x32 human face

### ISSUE THREAD

**Issue by twowwj** [ckkelvinchan/GLEAN#10]
Hi kelvin,
I want to input the size of 32x32 human face images and output the size of 1024x1024 using glean.
Does the model(glean_ffhq_16x) is trained only can be input the size of 64x64 images, output the size of 1024x1024?
Can I finish my test only by modifying the encoder and decoder?

looking forward to your reply!
thx

**Comment by ckkelvinchan** [comment]
One simple way is to upsample the image to 64x64. But this may not be ideal as the network is trained with inputs directly downsampled from the GT.

The best way is to retrain the network by setting `in_size=32`.
