### ISSUE TITLE
Wondering about the dataset used for training

### ISSUE THREAD

**Issue by zwb0** [ckkelvinchan/GLEAN#12]
Thanks for your great work.
  I'm wondering if you only use the cat class in LSUN for training 'cats', and cars in  LSUN for training 'cars'? Then what's the training data for the category of Bedroom and Towers? Or did you use all the categories in LSUN for training? 
  Thanks in advance!

**Comment by ckkelvinchan** [comment]
Hi @zwb0, thanks for your interest in our work. As shown in our paper, we use also LSUN for the other categories except human faces. 

<img width="752" alt="Screenshot 2021-12-03 at 4 32 16 PM" src="https://user-images.githubusercontent.com/7676947/144570957-65a575cf-dc65-44f1-9610-9c4d0aa0417a.png">

**Comment by zwb0** [comment]
Thanks for your reply,
  Yeah, I have found this table. But I'm wondering if you trained the model for 'cats', do you only use the cat category in LSUN or all the classes in LSUN for training? 
  Thanks a lot!

**Comment by ckkelvinchan** [comment]
For cats, we train only with cats in LSUN. Similar for others.

**Comment by zwb0** [comment]
Thanks for your reply!~

**Comment by ckkelvinchan** [comment]
You're welcome :)
