### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zwb0** [ckkelvinchan/GLEAN#13]
Hi,
    Thanks for your great work!
    I'm new in this area, so I'm confused about the dataset.
    I just downloaded celebA-HQ dataset from this link [https://drive.google.com/drive/folders/11Vz0fqHS2rXDb5pprgTjpD7S2BAJhi1P?usp=sharing], and I'm afraid my validation set (or the image name) is different from yours. So can you check whether my first 100 images are the same as your validation set?
    And Is it correct for me to train glean on all the 70,000 images on FFHQ, while validating and testing on these 100 images on celebA-HQ dateset?
![celebA-HQ-val-100](https://user-images.githubusercontent.com/18023358/149345174-4af85173-848b-4865-99e0-0601e006ac5b.png)

Thanks in advance!

**Comment by ckkelvinchan** [comment]
The validation set is the same as mine. And yes, we use all 70000 FFHQ images for training.

**Comment by zwb0** [comment]
Sorry to bother you again. I noticed that my test data are in '.jpg' format which is different from yours, which influenced my inference result. (And I have tried to convert them into png files, but the png images also differ from yours.) So I'm wording if you are convenient to share with me your 100 test images via link. 
Thanks a lot!

**Comment by ckkelvinchan** [comment]
I downloaded the jpg images and simply re-save them to png for convenience only.
