### ISSUE TITLE
Where is the code of GLEAN in mmgeneration?

### ISSUE THREAD

**Issue by ewrfcas** [ckkelvinchan/GLEAN#2]
Hi, I want to learn the codes of this good project. But no codes about GLEAN can be found in https://github.com/open-mmlab/mmgeneration.

**Comment by ckkelvinchan** [comment]
Hi, the code is in MMEditing: https://github.com/open-mmlab/mmediting.

**Comment by zhangyunming** [comment]
your link maybe is mmgeneration.

**Comment by ckkelvinchan** [comment]
Oh! Thank you very much. My mistake.
