### ISSUE TITLE
Some questions about the resizing method.

### ISSUE THREAD

**Issue by ewrfcas** [ckkelvinchan/GLEAN#4]
Hi, thanks for your kind response! I have another question about the resize method used in python. Since you have mentioned that the matlab default bicubic resize should be used in GLEAN. However, I think maybe the resize method is LINEAR_AREA?
Here is the resized result in python opencv (cv2)
bicubic:
![1009_bicubic](https://user-images.githubusercontent.com/12042259/121684888-e2724200-caf1-11eb-9b39-12f58d20e778.png)
area:
![1009_area](https://user-images.githubusercontent.com/12042259/121684942-f1f18b00-caf1-11eb-9d96-dbccdf783401.png)
Then, the output result of bicubic is 
![image](https://user-images.githubusercontent.com/12042259/121685035-0afa3c00-caf2-11eb-8790-a1efa76b118d.png)
And the result of area is
![image](https://user-images.githubusercontent.com/12042259/121685126-26654700-caf2-11eb-8f35-724f17d353e2.png)
It can be seen that area is much better than bicubic. But the area result still has some artifacts (hair). I think maybe the resize method still has some problems? The sample is named 1009.jpg in Celeba-HQ.

**Comment by ckkelvinchan** [comment]
The bicubic downsampling in MATLAB is different from the one in opencv. The one in MATLAB contains some anti-aliasing operations. Therefore, when you use the pre-trained GLEAN on the images downgraded by opencv, it is normal that you get a poor result. 

The result from `area` is better in this case but it is still far from optimal.

**Comment by ewrfcas** [comment]
Thanks I have tried matlab resize, and it works much better now
![image](https://user-images.githubusercontent.com/12042259/121686382-ab9d2b80-caf3-11eb-930e-7c0328175ad3.png)
