### ISSUE TITLE
Where can I find the datasets correspond to your meta-info 

### ISSUE THREAD

**Issue by twowwj** [ckkelvinchan/GLEAN#5]
Hi kelvin 
I want to try to reproduce the results of this nice work. But I can't find the dataset corresponding to /data/ celeA-HQ/ "meta_info_CelebAHQ_val100_GT.txt".
Where can I download it?

here is the error of log : FileNotFoundError: [Errno 2] No such file or directory: 'data/CelebA-HQ/BIx16_down/00001.png'

Thanks

**Comment by ckkelvinchan** [comment]
Hi, for the GT images, you can download them from [here](https://drive.google.com/drive/folders/11Vz0fqHS2rXDb5pprgTjpD7S2BAJhi1P). Then you can generate the LR images by using MATLAB `imresize` function.

**Comment by twowwj** [comment]
Thanks for your reply.
So, what I need to do is downloading the dataset of any resolution (for example, data128x128.zip)from the link, and then resize the shape using MATLAB.
By the way, what about the other dataset, like FFHQ or CAT.
I have just entered this field not long ago and I don’t know much about it.

Thx

**Comment by ckkelvinchan** [comment]
Different categories have different sizes. For instance, we use 1024 for human faces. That's why you should download the 1024x1024 version, and then downsample using MATLAB.

For the download link of other datasets used in our paper, please refer to the supplementary material of our paper. MATLAB `imresize` is also used for downsampling.

**Comment by twowwj** [comment]
I have followed the instruction [https://github.com/open-mmlab/mmediting/blob/master/docs/getting_started.md](here).
"CUDA_VISIBLE_DEVICES=0,2 GPUS=2 python tools/test.py configs/restorers/glean/glean_ffhq_16x.py work_dirs/glean_ffhq_16x_20210527-61a3afad.pth --out work_dirs/results/result.pkl --save-path preds/celea-hq"

I have organized the form of data, which is located in "$/mmediting/data/CelebA-HQ/BIx16_down"
but still, have a problem "FileNotFoundError: [Errno 2] No such file or directory: 'data/CelebA-HQ/BIx16_down/00001.png'"

**Comment by ckkelvinchan** [comment]
From this error, you should have no `data/CelebA-HQ/BIx16_down/00001.png'`. Please check carefully whether you have this image. For instance, the downloaded images are in `jpg` format. You should change them to `png`.

**Comment by wuyushuwys** [comment]
I am trying to get the datasets of cat faces (Cat Test dataset) but i can't find the dataset except its paper.

**Comment by ckkelvinchan** [comment]
> I am trying to get the datasets of cat faces (Cat Test dataset) but i can't find the dataset except its paper.

Here it is: https://web.archive.org/web/20150520175645/http://137.189.35.203/WebUI/CatDatabase/catData.html

**Comment by zwb0** [comment]
Hi, 
    I can only get the .jpg format images of the cat test dataset. Did you convert them into .png? Or did you directly download the .png version?
