### ISSUE TITLE
Bad Test Result

### ISSUE THREAD

**Issue by HWalkingMan** [ckkelvinchan/GLEAN#7]
Hi kelvin,
I have tested the model (released on [here](https://download.openmmlab.com/mmediting/restorers/glean/glean_cat_8x_20210614-d3ac8683.pth)) with Cat Test dataset, but I have obtained very poor test results. 
![00000800_007](https://user-images.githubusercontent.com/47980785/128593642-b620c548-caad-4014-8b4e-f26adc03595c.png)
At the same time, the metrics are also very unsatisfactory and far from the results given in the paper.
Could you give me some suggestions? Should I train model again or try something else?

**Comment by ckkelvinchan** [comment]
How do you obtain the low-resolution images?

**Comment by HWalkingMan** [comment]
For train data, I downloaded zip file from ([here](http://dl.yf.io/lsun/objects/cat.zip) from [lsun](https://www.yf.io/p/lsun)) , and edited code from [here](https://github.com/fyu/lsun/blob/master/data.py) to unzip mdb file and crop images. I used code from [here](https://github.com/NVlabs/stylegan/blob/master/dataset_tool.py) (line:425-430) to crop images. Finally, I got 29343 HR images. Then, I used resize function supported by opencv-python to downsmaple image to 32px with bicubic.

For test data, I downloaded zip file from [here](https://www.kaggle.com/crawford/cat-dataset),  and selected the pictures whose names are in [meta_info_Cat100_GT](https://github.com/ckkelvinchan/GLEAN/blob/main/data/cat_test/meta_info_Cat100_GT.txt).
Then, I used function from opencv-python to resize images and convert the file format. Finally, I got 100 HR image and 100 LR image in PNG format.

**Comment by ckkelvinchan** [comment]
The released model is for images downsampled by the MATLAB `imresize` function. Therefore, if you want to use the pre-trained model, please downsample the images with MATLAB. Otherwise, you can retrain the model using the degradation you want.

**Comment by youngAt19** [comment]
@HWalkingMan Hi,  I tried all the steps without opencv-resizing as what you did, but the train data looks so weird. Many images contain unrelated contents. Have you ever encouter this problem??
@ckkelvinchan Do you use the crop codes likes [here](https://github.com/NVlabs/stylegan/blob/master/dataset_tool.py)(line:425-430) when processing the LSUN-CAT?
![0548834473312216924342864fc6b3128e9e1353](https://user-images.githubusercontent.com/58137631/131333335-24b58a7b-f77f-40ae-9571-c14fcd831227.png)
![020416740886208102de575ce86466a6efa93722](https://user-images.githubusercontent.com/58137631/131333347-2fef655f-b0f4-42ff-b538-1abcda7754de.png)
![02039055972591998c7ec90839128609dce17b27](https://user-images.githubusercontent.com/58137631/131333350-0b63fd25-e4bc-43a6-b220-f95e6adbd894.png)

**Comment by ckkelvinchan** [comment]
We directly use `imresize` to generate the training data, as we want to make sure that the main object is not cropped out. 

But it is true that the aspect ratio could be modified. Someone would first center crop with size s x s, where s is the length of the shorter edge, and resize it to the desired size.

**Comment by youngAt19** [comment]
Thanks a lot! I'll try it.
